
library(shiny)
library(shinyalert)
library(mongolite)
library(dplyr)

# Read the name data
df <- read.csv("name_data.csv")

connection_string <- 
    paste0("mongodb+srv://glakin0:",
           keyring::key_get(service = "mongodb", username = "glakin0"), 
           "@firstcluster.wqhqh.mongodb.net/baby_name_helper?retryWrites=true&w=majority")

likCon <- mongo(#database = "baby_name_helper",
             collection = "liked_names",
             url = connection_string)


obsCon <- mongo(#database = "baby_name_helper",
    collection = "observed_names",
    url = connection_string)

# Create empty "observed" and "liked" dataframes that will contain observed
# and liked names
observed = data.frame(matrix(ncol = 5, nrow = 0))
colnames(observed) <- c("email", "name", "gender", "count", "rank")
liked = data.frame(matrix(ncol = 5, nrow = 0))
colnames(liked) <- c("email", "name", "gender", "count", "rank")

genders <- data.frame(gender = c("F", "M"),
                      gender_long = c("Girl", "Boy")
)

shinyServer(function(input, output) {

    # Create reactiveValues object to contain assorted values generated by 
    # the code
    values <- reactiveValues()
    
    # Create reactiveValues objects to house observed and liked dataframes
    obs <- reactiveValues(observed = observed)
    lik <- reactiveValues(liked = liked)
    
    # Shiny alert to request email address
    shinyalert(
        title = "Welcome to Baby Name Helper!",
        text = "Please enter your email",
        size = "s", 
        closeOnEsc = TRUE,
        closeOnClickOutside = FALSE,
        html = FALSE,
        type = "input",
        inputType = "text",
        inputValue = "",
        inputPlaceholder = "Email Address",
        showConfirmButton = TRUE,
        showCancelButton = FALSE,
        confirmButtonText = "OK",
        confirmButtonCol = "#AEDEF4",
        timer = 0,
        imageUrl = "",
        animation = TRUE
    )
    
    # Event: Clicking the "Suggest a Name" button
    observeEvent(input$suggest, {
        
        if(length(obs$observed$name) == 0) {
            db_obs <- obsCon$find(paste0('{"email":"',input$shinyalert,'"}'))
            if (length(db_obs$name > 0)) {
                obs$observed <- db_obs
            }
        }
        
        if(length(lik$liked$name) == 0) {
            db_lik <- likCon$find(paste0('{"email":"',input$shinyalert,'"}'))
            if (length(db_lik$name > 0)) {
                lik$liked <- db_lik
                output$likedHeader <- 
                    renderText({paste0("Your Saved ",genders[genders$gender == input$gender,]$gender_long ," Names")})
                output$liked <- 
                    renderText({paste(unlist(lik$liked[lik$liked[, "gender"] == input$gender, "name"]), collapse = ", ")})
            }
        }
        
        # if (input$rpt == "yes" | !file.exists(paste0("observed_names_",input$gender,".csv"))) {
        #     df_gender <- df[df$gender == input$gender,]
        # } else {
        #     observed_names <- read.csv(paste0("observed_names_",input$gender,".csv"))
        #     df_gender <- df[df$gender == input$gender & !(df$name %in% observed_names$name),]
        # }
        
        # Check if the repeat names option is toggled and limit the data accordingly
        if(input$rpt == "yes") {
            df_gender <- df[df$gender == input$gender,]
        } else {
            df_gender <- df[df$gender == input$gender & !(df$name %in% obs$observed[, "name"]),]
        }
        
        # Generate the suggested name and associated stats
        values$nameSuggestion <- sample(df_gender$name, size=1, prob=df_gender$frequency )
        values$nameRank <- round(df_gender[df_gender$name == values$nameSuggestion,]$rank)
        values$nameCount <- df_gender[df_gender$name == values$nameSuggestion,]$count
        
        email <- coalesce(input$shinyalert, "Unknown")
        # Check if name is already in observed DF, if not add it
        # Note the if logic is a bit hacky but it's written this way to account
        # for the fact that the same name may appear for both boys and girls
        if(!(input$gender %in% obs$observed[obs$observed[,"name"] == values$nameSuggestion,"gender"])) {
            new_nm <- data.frame(email, values$nameSuggestion, input$gender, values$nameCount, values$nameRank)
            colnames(new_nm) <- c("email", "name", "gender", "count", "rank")
            obs$observed <- rbind(obs$observed, new_nm)
            #Update the database
            obsCon$insert(new_nm)
        }
        
        output$test <- renderText({paste(unlist(obs$observed[,"name"]))})
        
        # Output the name and rank
        output$nameSuggestion <- renderText({
            values$nameSuggestion
        })
        output$nameRank <- renderText({
            paste0("Rank: ", values$nameRank)
        })
        
        # Output the section stating how many names have been viewed
        if (input$gender == 'F') {
            #values$observed <- length(observed_names$name)
            
            #values$observedCount <- sum(observed_names$count)
            output$observedNames <- renderText({
                paste0("Viewed <b>",
                       length(obs$observed[obs$observed[,"gender"] == "F","name"]),
                       "</b> names, representing <b>",
                       round(sum(obs$observed[obs$observed[,"gender"] == "F","count"])/sum(df[df$gender == input$gender,]$count),digits=2)*100, 
                       "%</b> of girls born in 2020")
            })
            
        } else {
            #values$observed <- length(observed_names$name)
            #values$observedCount <- sum(observed_names$count)
            
            output$observedNames <- renderText({
                paste0("Viewed <b>",
                       length(obs$observed[obs$observed[,"gender"] == "M","name"]),
                       "</b> names, representing <b>",
                       round(sum(obs$observed[obs$observed[,"gender"] == "M","count"])/sum(df[df$gender == input$gender,]$count),digits=2)*100, 
                       "%</b> of boys born in 2020")
            })
        }
        
        
        
        
        # Old version of handling observed names using .csv files - changed to
        # reactive dataframes
        
        # 
        # 
        # if(file.exists(paste0("observed_names_",input$gender,".csv"))) {
        #     observed_names <- read.csv(paste0("observed_names_",input$gender,".csv"))
        #     if(values$nameSuggestion %in% observed_names$name) {
        #         
        #     } else {
        #         new_name <- data.frame(values$nameSuggestion, values$nameCount, values$nameRank)
        #         names(new_name) = c("name", "count", "rank")
        #         observed_names <- rbind(observed_names, new_name)
        #         
        #         write.csv(observed_names, paste0("observed_names_",input$gender,".csv"), row.names = FALSE)
        #     } 
        #         
        # } else {
        #     observed_names <- data.frame(values$nameSuggestion, values$nameCount, values$nameRank)
        #     names(observed_names) = c("name", "count", "rank")
        #     write.csv(observed_names, paste0("observed_names_",input$gender,".csv"), row.names = FALSE)
        # }
        # 
        # if (input$gender == 'F') {
        #     values$observed <- length(observed_names$name)
        #     
        #     values$observedCount <- sum(observed_names$count)
        #     output$observedNames <- renderText({
        #         paste0("Viewed <b>",values$observed,"</b> names, representing <b>",
        #                round(values$observedCount/sum(df[df$gender == input$gender,]$count),digits=2)*100, 
        #                "%</b> of female babies born in 2020")
        #     })
        # 
        # } else {
        #     values$observed <- length(observed_names$name)
        #     values$observedCount <- sum(observed_names$count)
        #     
        #     output$observedNames <- renderText({
        #         paste0("Viewed <b>",values$observed,"</b> names, representing <b>",
        #                round(values$observedCount/sum(df[df$gender == input$gender,]$count),digits=2)*100, 
        #                "%</b> of male babies born in 2020")
        #     })
        # 
        # }
    })
    
    # Event: Clicking the "Save this Name" button
    observeEvent(input$save, {
        # if(file.exists(paste0("liked_names_",input$gender,".csv"))) {
        #     liked_names <- read.csv(paste0("liked_names_",input$gender,".csv"))
        #     if(values$nameSuggestion %in% liked_names$name) {
        #         
        #     } else {
        #         new_name <- data.frame(values$nameSuggestion, values$nameRank)
        #         names(new_name) = c("name", "rank")
        #         liked_names <- rbind(liked_names, new_name)
        #         write.csv(liked_names, paste0("liked_names_",input$gender,".csv"), row.names = FALSE)
        #         if (input$gender == 'F') {
        #             output$likedNames_F <- renderText({
        #                 length(liked_names$name)
        #             })
        #         } else {
        #             output$likedNames_M <- renderText({
        #                 length(liked_names$name) 
        #             })
        #         }
        #     }
        # } else {
        #     new_name <- data.frame(values$nameSuggestion, values$nameRank)
        #     names(new_name) = c("name", "rank")
        #     write.csv(new_name, paste0("liked_names_",input$gender,".csv"), row.names = FALSE)
        # }
        
        email <- coalesce(input$shinyalert, "Unknown")
        
        if(!(input$gender %in% lik$liked[lik$liked[,"name"] == values$nameSuggestion,"gender"])) {
            new_nm <- data.frame(email, values$nameSuggestion, input$gender, values$nameCount, values$nameRank)
            colnames(new_nm) <- c("email", "name", "gender", "count", "rank")
            lik$liked <- rbind(lik$liked, new_nm)
            #Update the database
            likCon$insert(new_nm)
            
        }
        
        # if(input$gender == "F") {
        #     output$likedHeader <- renderText({"Your Saved Girl Names"})
        #     output$liked <- renderText({paste(unlist(lik$liked[lik$liked[, "gender"] == "F", "name"]), collapse = ", ")})
        # } else {
        #     output$likedHeader <- renderText({"Your Saved Boy Names"})
        #     output$liked <- renderText({paste(unlist(lik$liked[lik$liked[, "gender"] == "M", "name"]), collapse = ", ")})
        # }
        
        output$likedHeader <- 
            renderText({paste0("Your Saved ",genders[genders$gender == input$gender,]$gender_long ," Names")})
        output$liked <- 
            renderText({paste(unlist(lik$liked[lik$liked[, "gender"] == input$gender, "name"]), collapse = ", ")})
        
    })
    
    observeEvent(input$email, {
        email <- input$shinyalert
        output$email <- renderText({email})
        
    })
    

})
